### ISSUE TITLE
Trouver une autre solution que Crisp pour les mailings

### ISSUE THREAD

**Issue by Emelinejy** [incubateur-ademe/territoires-en-transitions#1140]
- [x] msg sur channel biz-dév'
- [x] Choisir une solution pour mailing à partir du 23/05
- [x] Test Send in blue 
- [x] Envoi mail Test Send in Blue
- [x] Proposition / Demo Emeline et Nicolas 

Ok vu avec Emeline et Nicolas - SendinBlue // Passer sur la version payante pour les premiers envois

**Comment by penelopel** [comment]
Si l'on souhaite mettre en place Crisp, on pourra également l'utiliser pour l'envoi de mailing aux utilisateurs
