### ISSUE TITLE
Finaliser les maquettes de la gestion des caractéristiques - cas 2 #1372

### ISSUE THREAD

**Issue by Nickvalley** [incubateur-ademe/territoires-en-transitions#1531]

**Comment by cami-na** [comment]
[Proposition de maquettes](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=0%3A1) à finaliser une fois toutes les questions et l'organisation des contenus revus ensemble et validés par Émeline et Nicolas

**Comment by cami-na** [comment]
Validé avec Florian, en attente d'une dernière revue d' @Emelinejy stp :)
[- Spécifications](https://github.com/betagouv/territoires-en-transitions/issues/1372#issuecomment-1039111619)
[- Maquettes cas 2 ](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=0%3A1)
[- Maquettes cas 3 ](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=0%3A1)

**Comment by cami-na** [comment]
Il reste à faire :
- l'ordre des questions dans le markdown (+ les mots en gras)
- question de décocher les boutons radio à voir avec les designers transverses
