### ISSUE TITLE
T - afficher les niveau labellisation

### ISSUE THREAD

**Issue by derfurth** [incubateur-ademe/territoires-en-transitions#1555]

**Comment by cami-na** [comment]
### Spécifications
https://github.com/betagouv/territoires-en-transitions/issues/453#issuecomment-1035227214
cf User story #453 


### Maquettes
[Lien Figma](https://www.figma.com/file/YhEoPD2YxqHuEaPn8nKWql/Maquettes-2k22?node-id=0%3A1)
Uniquement le bloc "Non labellisé" ou "Niveau de labellisation actuel" avec les 5 étoiles et les infobulles au survol
