### ISSUE TITLE
Proposer priorisation des quick-win liés à audit UX de l'application

### ISSUE THREAD

**Issue by Emelinejy** [incubateur-ademe/territoires-en-transitions#1617]
Créer une colonne dans le jardin avec les tâches

**Comment by cami-na** [comment]
[Audit UX](https://territoires-en-transitions.notion.site/Audit-UX-de-l-application-bb84bd60eca3442a83ae73b874b88bda)
- Vert : remarque en cours de traitement ou traitée
- Jaune : tâches à intégrer dans le prochain sprint
- Violet : sujets liés à l'investigation en cours sur la vue d'ensemble et la vue plan d'actions des référentiels 
- Sans couleur : à discuter
